name: Release a patch

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2.5.0
        with:
          java-version: 17
          distribution: zulu
      - run: |
          today=$(date -d today +%Y-%m-%d)
          yesterday=$(date -d yesterday +%Y-%m-%d)
          today_url="https://flix.dev/nightly/flix-${today}.jar"
          yesterday_url="https://flix.dev/nightly/flix-${yesterday}.jar"
          curl -L -f "${today_url}" > flix.jar || curl -L -f "${yesterday_url}" > flix.jar
          java -jar flix.jar build
          java -jar flix.jar build-pkg
          java -jar flix.jar build-jar
          echo "fcwg_version=$(java -jar fcwg.jar --version)" >> $GITHUB_ENV
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          prerelease: true
          tag_name: ${{ env.fcwg_version }}
          files: |
            fcwg.jar
            fcwg.fpkg
            
